import os

import pytest
from azure.ai.projects import AIProjectClient
from azure.ai.projects.models import AgentClusterInsightRequest, Insight
from azure.identity import DefaultAzureCredential


@pytest.mark.integration
def test_generate():
    with (
        DefaultAzureCredential() as credential,
        AIProjectClient(
            endpoint=os.environ["AZURE_AI_PROJECT_ENDPOINT"],
            credential=credential,
        ) as client,
    ):
        generated_insight = client.beta.insights.generate(
            insight=Insight(
                display_name="Temporary insight generated by pytest.",
                request=AgentClusterInsightRequest(agent_name="weather-agent"),
            ),
        )

        assert generated_insight is not None


@pytest.mark.integration
def test_get():
    with (
        DefaultAzureCredential() as credential,
        AIProjectClient(
            endpoint=os.environ["AZURE_AI_PROJECT_ENDPOINT"],
            credential=credential,
        ) as client,
    ):
        generated_insight = client.beta.insights.generate(
            insight=Insight(
                display_name="Temporary insight generated by pytest.",
                request=AgentClusterInsightRequest(agent_name="weather-agent"),
            ),
        )

        retrieved_insight = client.beta.insights.get(
            insight_id=generated_insight.insight_id,
        )

        assert retrieved_insight is not None


@pytest.mark.integration
def test_list():
    with (
        DefaultAzureCredential() as credential,
        AIProjectClient(
            endpoint=os.environ["AZURE_AI_PROJECT_ENDPOINT"],
            credential=credential,
        ) as client,
    ):
        listed_insights = list(client.beta.insights.list())

        assert isinstance(listed_insights, list)
